"""empty message

Revision ID: 0d5a445f87e1
Revises: 466c03c22c0c
Create Date: 2019-11-14 10:40:13.451134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d5a445f87e1'
down_revision = '466c03c22c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('img_id', sa.Integer(), nullable=True, comment='关联图片ID'))
    op.drop_column('category', 'topic_img_id')
    op.alter_column('product', 'img_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='关联图片ID',
               existing_comment='图片外键',
               existing_nullable=True)
    op.alter_column('theme', 'head_img_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='专题列表页，头图ID',
               existing_comment='专题列表页，头图',
               existing_nullable=False)
    op.alter_column('theme', 'topic_img_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='主题图ID',
               existing_comment='主题图，外键',
               existing_nullable=False)
    op.alter_column('theme_product', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='商品ID',
               existing_comment='商品外键',
               existing_nullable=False)
    op.alter_column('theme_product', 'theme_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='主题ID',
               existing_comment='主题外键',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('theme_product', 'theme_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='主题外键',
               existing_comment='主题ID',
               existing_nullable=False)
    op.alter_column('theme_product', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='商品外键',
               existing_comment='商品ID',
               existing_nullable=False)
    op.alter_column('theme', 'topic_img_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='主题图，外键',
               existing_comment='主题图ID',
               existing_nullable=False)
    op.alter_column('theme', 'head_img_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='专题列表页，头图',
               existing_comment='专题列表页，头图ID',
               existing_nullable=False)
    op.alter_column('product', 'img_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='图片外键',
               existing_comment='关联图片ID',
               existing_nullable=True)
    op.add_column('category', sa.Column('topic_img_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='外键，关联image表'))
    op.drop_column('category', 'img_id')
    # ### end Alembic commands ###
