"""empty message

Revision ID: 154758cd938d
Revises: 0d5a445f87e1
Create Date: 2019-11-17 11:09:11.865321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '154758cd938d'
down_revision = '0d5a445f87e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('summary', sa.String(length=100), nullable=True, comment='描述'))
    op.drop_column('category', 'description')
    op.add_column('theme', sa.Column('summary', sa.String(length=255), nullable=True, comment='专题描述'))
    op.drop_column('theme', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme', sa.Column('description', mysql.VARCHAR(length=255), nullable=True, comment='专题描述'))
    op.drop_column('theme', 'summary')
    op.add_column('category', sa.Column('description', mysql.VARCHAR(length=100), nullable=True, comment='描述'))
    op.drop_column('category', 'summary')
    # ### end Alembic commands ###
