"""empty message

Revision ID: 466c03c22c0c
Revises: cdf282034109
Create Date: 2019-11-13 15:49:04.431022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '466c03c22c0c'
down_revision = 'cdf282034109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'stock',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='库存量')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'stock',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='库存量')
    # ### end Alembic commands ###
