"""empty message

Revision ID: 90413ee853a8
Revises: 
Create Date: 2019-11-30 20:59:23.941530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90413ee853a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banner_item', 'content_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='导向内容表ID，根据不同的type导向不同的表')
    op.alter_column('banner_item', 'type',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True,
               existing_comment='跳转类型: 可能导向商品，可能导向专题，可能导向其他 0 无导向 1 导向商品 2 导向专题')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banner_item', 'type',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False,
               existing_comment='跳转类型: 可能导向商品，可能导向专题，可能导向其他 0 无导向 1 导向商品 2 导向专题')
    op.alter_column('banner_item', 'content_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='导向内容表ID，根据不同的type导向不同的表')
    # ### end Alembic commands ###
